### ISSUE TITLE
0 is not a valid selector

### ISSUE THREAD

**Issue by Huaraz2** [reekers/language-vbscript#6]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 0.209.0-d965eb7
**System**: Ubuntu 15.04
**Thrown From**: [language-vbscript](https://github.com/reekers/language-vbscript) package, v0.4.0

### Stack Trace

Failed to activate the language-vbscript package

```
At 0 is not a valid selector in /home/huaraz2/.atom/packages/language-vbscript/package.json

SyntaxError: 0 is not a valid selector in /home/huaraz2/.atom/packages/language-vbscript/package.json
    at exports.validateSelector (/usr/share/atom/resources/app.asar/node_modules/clear-cut/index.js:115:19)
    at CommandRegistry.module.exports.CommandRegistry.add (/usr/share/atom/resources/app.asar/src/command-registry.js:44:9)
    at /usr/share/atom/resources/app.asar/src/package.js:753:70
    at Package.module.exports.Package.subscribeToActivationCommands (/usr/share/atom/resources/app.asar/src/package.js:782:11)
    at /usr/share/atom/resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
  at /home/huaraz2/.atom/packages/language-vbscript/package.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "highlight-line"
    ],
    "themes": [
      "one-dark-ui",
      "the--matrix-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.2.2
color-picker, v2.0.4
minimap, v4.10.0
the--matrix-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by reekers** [comment]
Do you still have this issue with the new version?
